'use client';
import { useEffect, useState } from 'react';
import { Download, Circle, Square } from 'lucide-react';
import { Modal } from './common';
import { subscribeProcessStatus } from '@/lib/process-client';
type Batch={id:string;startedAt:string;stoppedAt:string|null};
export default function ProcessControls() {
  const [delivery,setDelivery]=useState({pending:0,error:'',activeId:null as string|null,dropped:0});
  const [open,setOpen]=useState(false),[active,setActive]=useState<Batch|null>(null),[batches,setBatches]=useState<Batch[]>([]),[selected,setSelected]=useState(''),[username,setUsername]=useState(''),[demo,setDemo]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');
  async function refresh(){try{const r=await fetch('/api/process-recording?admin=1',{cache:'no-store',signal:AbortSignal.timeout(5000)}),d=await r.json();if(!r.ok)throw Error(d.error);setActive(d.active);setBatches(d.recordings||[]);setSelected(id=>id||(d.active?.id||d.recordings?.[0]?.id||''));}catch(e){setError((e as Error).message||'Could not load recording status.');}}
  useEffect(()=>{if(!open)return;void refresh();const timer=setInterval(()=>void refresh(),10000);return()=>clearInterval(timer);},[open]);
  useEffect(()=>subscribeProcessStatus(setDelivery),[]);
  async function change(action:'start'|'stop'){setBusy(true);setError('');try{const r=await fetch('/api/process-recording',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action}),signal:AbortSignal.timeout(8000)}),d=await r.json();if(!r.ok)throw Error(d.error);setActive(d.active);if(d.recording)setSelected(d.recording.id);window.dispatchEvent(new Event('cwrite-process-control'));await refresh();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  const query=new URLSearchParams({recordingId:selected,username:username.trim(),includeDemo:String(demo)});
  return <div className="process-controls" data-process-ignore="true"><button className="process-open" onClick={()=>setOpen(true)}><Circle size={14} fill={active?'#ca5555':'none'}/>Behavior records</button>{open&&<Modal title="Student behavior records" onClose={()=>setOpen(false)}><div data-process-ignore="true" className="process-panel"><p role="status">{active?'Recording student activity':'Recording is off'}</p><p className="field-hint">Records include writing, drawing, AI use, pauses and navigation. Student work continues normally.</p><button className="purple-button" disabled={busy} onClick={()=>void change(active?'stop':'start')}>{active?<Square size={16}/>:<Circle size={16}/>} {busy?'Updating…':active?'Stop recording':'Start recording'}</button>{active&&<p className="field-hint">Started {new Date(active.startedAt).toLocaleString()}</p>}<label>Recording batch<select value={selected} onChange={e=>setSelected(e.target.value)}><option value="">Choose a recording</option>{batches.map(b=><option key={b.id} value={b.id}>{new Date(b.startedAt).toLocaleString()}{b.stoppedAt?' · stopped':' · recording'}</option>)}</select></label><label>Student username <small>(leave blank for all)</small><input value={username} onChange={e=>setUsername(e.target.value)} placeholder="All students"/></label><label className="process-check"><input type="checkbox" checked={demo} onChange={e=>setDemo(e.target.checked)}/>Include Tony test records</label><div className="process-export-buttons"><a className="outline-button" aria-disabled={!selected} href={selected?'/api/process-export?'+query+'&format=xlsx':undefined}><Download size={16}/>Export Excel</a><a className="outline-button" aria-disabled={!selected} href={selected?'/api/process-export?'+query+'&format=csv':undefined}>CSV</a></div><p className="field-hint">Export is available after stopping. Offline records may arrive later; export again after students reconnect.</p>{delivery.error&&<p role="status" className="field-hint">This browser: {delivery.error}{delivery.dropped?` (${delivery.dropped} uncached records)`:""}</p>}{error&&<p role="alert" className="error-text">{error}</p>}</div></Modal>}</div>;
}
