import {createServer} from 'node:http';
import {timingSafeEqual} from 'node:crypto';
import {execFile} from 'node:child_process';
import {promisify} from 'node:util';
import {mkdtemp,writeFile,rm} from 'node:fs/promises';
import {join} from 'node:path';
import {tmpdir} from 'node:os';
import sharp,{type OverlayOptions} from 'sharp';
import {prisma} from '../lib/prisma';
import {createSeedanceTask,readSeedanceTask,ArkVideoError} from '../lib/ark-video';
import {videoAsset} from '../lib/video-assets';
import {storeVideoFile,videoAccessUrl} from '../lib/video-storage';
import {renderVideoClip,mergeVideoClips} from '../lib/video-render';
import {DRAMA_ACTOR_WIDTH} from '../lib/drama';
import type {Story,DramaScene} from '../lib/types';
import type {VideoBeat} from '../lib/video-pipeline';
const run=promisify(execFile);
async function main(){
const required=['DATABASE_URL','ARK_API_KEY','TOS_ACCESS_KEY_ID','TOS_SECRET_ACCESS_KEY','TOS_BUCKET','TOS_REGION','TOS_ENDPOINT','VIDEO_WORKER_SECRET'];
const missing=required.filter(key=>!process.env[key]);
if(missing.length)throw new Error(`Missing worker settings: ${missing.join(', ')}`);
if(process.env.VIDEO_WORKER_SECRET!.length<32)throw new Error('Use a worker secret of at least 32 characters.');
await run('ffmpeg',['-version']);
let stopping=false,lastPoll=0;
const lease=()=>new Date(Date.now()+10*60000);
type SavedPlan={story:Story;groups:{sceneId:string;sequence:number;duration:number;beats:VideoBeat[]}[]};

async function reference(scene:DramaScene,story:Story,path:string){
    const layers:OverlayOptions[]=[];
    for(const actor of scene.actors){
        const cast=story.characterSnapshots.find(c=>c.id===actor.characterId);if(!cast)throw new Error('An actor is missing from the saved cast.');
        const width=Math.round(1280*DRAMA_ACTOR_WIDTH/100*actor.scale);
        let picture=sharp(await videoAsset(cast.spriteUrl||cast.imageUrl)).resize({width,height:720,fit:'inside'});
        if(actor.flipped)picture=picture.flop();
        const {data,info}=await picture.png().toBuffer({resolveWithObject:true});
        layers.push({input:data,left:Math.max(0,Math.min(1280-info.width,Math.round(actor.x/100*1280-info.width/2))),top:Math.max(0,Math.min(720-info.height,Math.round(actor.y/100*720-info.height)))});
    }
    await sharp(await videoAsset(scene.backgroundImageUrl)).resize(1280,720,{fit:'cover'}).composite(layers).png().toFile(path);
}
async function downloadStored(ref:string,path:string){
    // A signed URL generated by our own storage client, never a client-provided URL.
    const response=await fetch(videoAccessUrl(ref),{redirect:'error',signal:AbortSignal.timeout(120000)});
    if(!response.ok||!response.body)throw new Error('Stored clip could not be read.');
    const {createWriteStream}=await import('node:fs');const {pipeline}=await import('node:stream/promises');const {Readable}=await import('node:stream');
    await pipeline(Readable.fromWeb(response.body as never),createWriteStream(path));
}
async function processJob(id:string){
    const job=await prisma.videoJob.findUniqueOrThrow({where:{id},include:{clips:{orderBy:{sequence:'asc'}}}});
    const plan=job.plan as unknown as SavedPlan;
    if(!plan.story||!plan.groups)throw new Error('This old video plan needs to be recreated.');
    // Recovery after a crash between a provider submission and saving its task id must never submit again silently.
    const uncertain=job.clips.find(c=>c.status==='submitting'||c.status==='needs_confirmation');
    if(uncertain){await prisma.videoJob.update({where:{id},data:{status:'needs_confirmation',errorCode:'needs_confirmation',errorMessage:'A submission result is unknown. Check the provider task history before choosing to pay for another attempt.'}});return;}
    const dir=await mkdtemp(join(tmpdir(),'cwrite-video-'));
    const renewal=setInterval(()=>void prisma.videoJob.update({where:{id},data:{leaseUntil:lease()}}).catch(()=>undefined),30000);
    try{
        const files:string[]=[];
        const names=Object.fromEntries(plan.story.characterSnapshots.map(c=>[c.id,c.name]));
        for(const initial of job.clips){
            let clip=await prisma.videoClip.findUniqueOrThrow({where:{id:initial.id}});
            const group=plan.groups.find(g=>g.sequence===clip.sequence);if(!group)throw new Error('Clip plan is missing.');
            const rendered=join(dir,`${clip.sequence}.mp4`);
            if(clip.storedUrl){await downloadStored(clip.storedUrl,rendered);files.push(rendered);continue;}
            if(!clip.providerTaskId){
                const scene=plan.story.canvas.drama!.scenes.find(s=>s.id===clip.sceneId);if(!scene)throw new Error('Scene is missing.');
                const ref=join(dir,`ref-${clip.sequence}.png`);await reference(scene,plan.story,ref);
                const stored=await storeVideoFile(`videos/${job.userId}/${id}/reference-${clip.sequence}.png`,ref,'image/png');
                const motion=group.beats.map(b=>`${b.kind}: ${b.characterId?names[b.characterId]||'Character':''}. ${b.kind==='thought'?'Quiet reflective pause; do not speak.':b.kind==='dialogue'?'Small speaking gesture, other actors listen.':'Steady establishing shot.'}`).join('\n');
                await prisma.videoClip.update({where:{id:clip.id},data:{status:'submitting'}});
                let taskId:string;
                try{taskId=await createSeedanceTask(`Animate this exact stage gently. Preserve the cast, costumes and positions. No text, subtitles or new actors. No speech audio.\n${motion}`,videoAccessUrl(stored),clip.duration,job.model);}
                catch(error){
                    const uncertain=!(error instanceof ArkVideoError)||error.code==='needs_confirmation'||error.status>=500;
                    await prisma.videoClip.update({where:{id:clip.id},data:{status:uncertain?'needs_confirmation':'failed',error:'Video submission did not complete.'}});
                    await prisma.videoJob.update({where:{id},data:{status:uncertain?'needs_confirmation':'failed',errorCode:uncertain?'needs_confirmation':'provider_error',errorMessage:uncertain?'Submission result unknown. Check provider history before a paid retry.':'The provider rejected this clip. You may retry the failed clip.'}});return;
                }
                clip=await prisma.videoClip.update({where:{id:clip.id},data:{providerTaskId:taskId,status:'generating'}});
                await prisma.videoJob.update({where:{id},data:{status:'generating'}});
            }
            if(!clip.sourceUrl){
                const task=await readSeedanceTask(clip.providerTaskId);
                if(task.status==='failed'){await prisma.videoClip.update({where:{id:clip.id},data:{status:'failed',error:'The provider could not generate this clip.'}});await prisma.videoJob.update({where:{id},data:{status:'failed',errorCode:'provider_failed',errorMessage:'This clip failed. Completed clips are kept.'}});return;}
                if(task.status!=='succeeded')return;
                if(!task.videoUrl)throw new Error('Provider returned no video.');
                clip=await prisma.videoClip.update({where:{id:clip.id},data:{status:'rendering',sourceUrl:task.videoUrl}});
            }
            await prisma.videoJob.update({where:{id},data:{status:'rendering'}});
            const raw=join(dir,'raw.mp4');await writeFile(raw,await videoAsset(clip.sourceUrl,300*1024*1024));
            await renderVideoClip(dir,`${clip.sequence}.mp4`,clip.duration,group.beats,names);
            await prisma.videoJob.update({where:{id},data:{status:'storing'}});
            const storedUrl=await storeVideoFile(`videos/${job.userId}/${id}/clip-${clip.sequence}.mp4`,rendered,'video/mp4');
            await prisma.videoClip.update({where:{id:clip.id},data:{storedUrl,status:'stored'}});files.push(rendered);
        }
        await mergeVideoClips(dir,files.length);
        const outputUrl=await storeVideoFile(`videos/${job.userId}/${id}/final.mp4`,join(dir,'final.mp4'),'video/mp4');
        await prisma.videoJob.update({where:{id},data:{status:'ready',outputUrl,errorCode:'',errorMessage:''}});
    }finally{clearInterval(renewal);await rm(dir,{recursive:true,force:true});}
}
async function tick(){
    lastPoll=Date.now();
    const candidates=await prisma.videoJob.findMany({where:{status:{in:['planning','generating','rendering','storing']},OR:[{leaseUntil:null},{leaseUntil:{lt:new Date()}}]},orderBy:{createdAt:'asc'},take:5});
    for(const job of candidates){
        const claim=await prisma.videoJob.updateMany({where:{id:job.id,OR:[{leaseUntil:null},{leaseUntil:{lt:new Date()}}]},data:{leaseUntil:lease()}});
        if(!claim.count)continue;
        try{await processJob(job.id);}catch{await prisma.videoJob.update({where:{id:job.id},data:{status:'failed',errorCode:'worker_failed',errorMessage:'The video could not finish. Saved clips are kept; retry to resume.'}});}finally{await prisma.videoJob.update({where:{id:job.id},data:{leaseUntil:null}});}
    }
}
const secret=Buffer.from(`Bearer ${process.env.VIDEO_WORKER_SECRET}`);
const server=createServer(async(req,res)=>{
    const supplied=Buffer.from(req.headers.authorization||'');
    if(supplied.length!==secret.length||!timingSafeEqual(supplied,secret)){res.writeHead(401).end();return;}
    if(req.method!=='GET'||req.url!=='/health'){res.writeHead(404).end();return;}
    const ready=!stopping&&Date.now()-lastPoll<15*60000;
    res.writeHead(ready?200:503,{'Content-Type':'application/json'}).end(JSON.stringify({ready,version:1}));
});
server.listen(Number(process.env.PORT||8080),'0.0.0.0');
for(const signal of ['SIGTERM','SIGINT'] as const)process.on(signal,()=>{stopping=true;server.close();});
while(!stopping){try{await tick();}catch{console.error('Video worker database check failed.');}if(!stopping)await new Promise(resolve=>setTimeout(resolve,5000));}
await prisma.$disconnect();
}
void main().catch(()=>{console.error('Video worker could not start. Check configuration and database migrations.');process.exitCode=1;});
